// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_q4fkQ6lR8ThQcVqqFJZsBZ5JCC813V4',
    appId: '1:910602147715:web:3155b69ead0d3fc43a48b6',
    messagingSenderId: '910602147715',
    projectId: 'expense-tracker-5ebd5',
    authDomain: 'expense-tracker-5ebd5.firebaseapp.com',
    storageBucket: 'expense-tracker-5ebd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjAOV1vQcg-E3A8Bfiw2AitnA-DWNAo4c',
    appId: '1:910602147715:android:9a1996acd98e1e083a48b6',
    messagingSenderId: '910602147715',
    projectId: 'expense-tracker-5ebd5',
    storageBucket: 'expense-tracker-5ebd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKyaqtjanccF4k-0Wr54cpRNi-sTKHQoI',
    appId: '1:910602147715:ios:990effae63e347243a48b6',
    messagingSenderId: '910602147715',
    projectId: 'expense-tracker-5ebd5',
    storageBucket: 'expense-tracker-5ebd5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKyaqtjanccF4k-0Wr54cpRNi-sTKHQoI',
    appId: '1:910602147715:ios:990effae63e347243a48b6',
    messagingSenderId: '910602147715',
    projectId: 'expense-tracker-5ebd5',
    storageBucket: 'expense-tracker-5ebd5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_q4fkQ6lR8ThQcVqqFJZsBZ5JCC813V4',
    appId: '1:910602147715:web:3093ccc184af9c503a48b6',
    messagingSenderId: '910602147715',
    projectId: 'expense-tracker-5ebd5',
    authDomain: 'expense-tracker-5ebd5.firebaseapp.com',
    storageBucket: 'expense-tracker-5ebd5.firebasestorage.app',
  );
}
